### ISSUE TITLE
bbmri.de goes MII-KDS

### ISSUE THREAD

**Issue by CeciliaEngels** [medizininformatik-initiative/kerndatensatzmodul-biobank#20]
Bitte um Prüfen des Datensatzes: https://simplifier.net/bbmri.de, der auch Grundlage ist, für https://simplifier.net/oncology/oncospecimen und Überlegungen, wie eine Einbeziehung/ Angleichung/ Kompatibilität ermöglicht werden kann.

**Comment by noemide** [comment]
Made obsolete by MIABIS
